apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: fronted-app
        type: frontend
    spec:
      containers:
        - name:  frontend-container
          image: nginx:1.19.4 # se a versão estiver incorreta, a aplicação não vai parar, só não atualizará
  selector:
    matchLabels:
      type: frontend
  replicas: 6
